### ISSUE TITLE
OLED monitor error with i1 Display

### ISSUE THREAD

**Issue by seatrope** [pacsdisplay/pacsdisplay#3]
Hi Nick and Michael,

Thank you for this amazing piece of software. However, I am running into an issue where an error is sent both during the 1786 palette calibration as well as on the i1Meter mode, at the beginning of the calibration or while measuring a full black area of the screen, with my OLED monitor. The black levels being so low on a OLED type monitor may have resulted in something too low to measure (even at max monitor brightness). With the i1 Meter it asks with the ambient light cover is open (it is). Moving a brighter area under the i1 instantly gives expected readings. Everything works great with this i1 on a conventional backlit Dell UP2715k.
Thanks!

**Comment by nickbevins** [comment]
Full black on an OLED will essentially be 0 nit - unless there is a significant ambient contribution. The i1display photometer with Argyll CMS's spotread won't be able to get a reading. I've seen this on some ultrasound displays that use OLEDs. I've never tried to run the full calibration on one of these - but this is the behavior I would've expected.

Since it is *never* advisable to use 0 nit as the starting luminance on a DICOM GSDF calibrated display, is it possible to adjust the Lmin on the OSD settings of the display? That should give the meter something to measure and continue with the process. It will also give the LUT generation process a greater palette to use when building the LUT because anything less than 0.5-ish nit would've been useless anyway.

**Comment by seatrope** [comment]
thanks for the quick reply Nick!

unfortunately there is no option for increasing the Lmin for this display. It's counterintuitive, that an OLED display with essentially infinite contrast ratio falls short in this respect. If you have time, would appreciate an explanation of why 0 nit as a starting luminance is never advisable? Do not understand the theory leading to this.

Thanks again for everything!!

**Comment by nickbevins** [comment]
Happy to help

> unfortunately there is no option for increasing the Lmin for this display.

Page 36 of the [user's guide](https://downloads.dell.com/manuals/all-products/esuprt_display_projector/esuprt_display/dell-up2715k-monitor_user%27s%20guide_en-us.pdf "UP2715K User's Guide") discusses the operation for adjusting the contrast of the display. I would guess that changing that value should increase the minimum luminance output by the display. Give it a try and see if it works.

> If you have time, would appreciate an explanation of why 0 nit as a starting luminance is never advisable? Do not understand the theory leading to this.

There are several values to consider when establishing the luminance characteristics of a display for viewing medical images. The key thing to keep in mind is that you want to maintain consistent image presentation between different displays that may be used in the imaging chain. Since virtually all medical imaging systems use the DICOM standard for the storage and transmission of data, you should use the DICOM GSDF luminance response function. This is what pacsDisplay will try to accomplish when generating the LUT based on your uncalibrated luminance response (uLR) file. Generation of the LUT requires you to select a minimum and maximum operating luminance based on the palette. Contrary to the way most think about display calibration, you want to first think about your ambient settings and minimum luminance. This is where you'll lose the most visual information if it's not set up correctly. The general recommendation is that your minimum luminance should be four times the ambient luminance. However, you also don't want to make the ambient *illuminance* as dark as possible to avoid visual strain as you try to look at other things (e.g., keyboard, papers, etc.). If you keep the room dim, but not pitch black - think 25-50 lux. That level of illuminance should give you about 0.1 to 0.2 nit for ambient luminance depending on the diffuse reflection properties of the display's surface. Using the 4x rule, that'll put your Lmin at 0.4 to 0.8 nit, for an L'min (Lmin + Lamb) of 0.5 to 1.0 nit. The Dell UP2715K advertises an Lmax of 350 nit, which is perfect for a luminance ratio of 350 with L'min of 1.0 nit. While 350 for a luminance ratio may sound pitiful compared to the near infinite contrast ratio of the OLED, your visual system rapidly loses the ability to resolve that contrast near the limits of the luminance curve. Keeping it at 350 minimizes those losses and allows the GSDF to better accomplish it's goal. 

For most information, I'd suggest the [ACR-AAPM-SIIM Technical Standard for the Electronic Practice of Medical Imaging](https://www.acr.org/-/media/ACR/Files/Practice-Parameters/Elec-Practice-MedImag.pdf) and [AAPM Report 270: Display Quality Assurance](https://www.aapm.org/pubs/reports/RPT_270.pdf).

I'm going to close this issue since I don't think you should use the low luminances for calibration. If someone wanted to modify the code to allow the calibration to skip the first *x* gray level steps, that would probably be a way to avoid needing to change the minimum luminance in the OSD settings. However, that would reduce the size of the palette for the LUT generation, so I don't really thing that's a good idea, either.
